name: Blackjack Python Package
on: [push, pull_request]

jobs:
  build:
    runs_on: ubuntu_latest
    strategy:
      matrix:
        python-version: [3.7]
      steps:
        - users: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          usees: actions/setup-python@v1
          with:
            python-versiob: ${{ matrix.python-version }}
        - name: Test with pytest
          run: |
            pip install pytest
            pytest --verbose